/**
 * Builds all MCP App HTML pages from Preact sources in src/app-sources/.
 * Each app is compiled to a self-contained IIFE bundle, wrapped with the shared
 * CSS design system and postMessage bridge, and written to src/apps/<name>.ts
 * as an exported function. Run via: bun run build:apps
 */
import { SHARED_CSS } from './theme';
import { BRIDGE_BOOTSTRAP_JS } from '../src/utils/apps';

interface AppDef {
  dir: string;
  fn: string;
  title: string;
}

const APPS: AppDef[] = [
  { dir: 'console',    fn: 'buildConsoleHtml',          title: 'Console Logs' },
  { dir: 'network',    fn: 'buildNetworkDashboardHtml',  title: 'Network' },
  { dir: 'flamegraph', fn: 'buildFlamegraphHtml',        title: 'Flamegraph' },
  { dir: 'errors',     fn: 'buildErrorsHtml',            title: 'Errors' },
  { dir: 'redux',      fn: 'buildReduxHtml',             title: 'Redux State' },
  { dir: 'navigation', fn: 'buildNavigationHtml',        title: 'Navigation' },
  { dir: 'components', fn: 'buildComponentsHtml',        title: 'Component Tree' },
];

let failed = false;

for (const app of APPS) {
  process.stdout.write(`Building ${app.dir}... `);

  const result = await Bun.build({
    entrypoints: [`src/app-sources/${app.dir}/index.tsx`],
    target: 'browser',
    format: 'iife',
    minify: true,
    bundle: true,
  });

  if (!result.success || result.outputs.length === 0) {
    console.error('FAILED');
    for (const log of result.logs) console.error(log);
    failed = true;
    continue;
  }

  const bundle = await result.outputs[0].text();

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${app.title}</title>
<style>${SHARED_CSS}</style>
</head>
<body>
<div id="app"></div>
<script>${BRIDGE_BOOTSTRAP_JS}</script>
<script>${bundle}</script>
</body>
</html>`;

  const ts = `// AUTO-GENERATED by scripts/build-apps.ts — do not edit manually\nexport function ${app.fn}(): string {\n  return ${JSON.stringify(html)};\n}\n`;

  await Bun.write(`src/apps/${app.dir}.ts`, ts);
  console.log('✓');
}

if (failed) {
  console.error('Some apps failed to build.');
  process.exit(1);
}
console.log('All apps built successfully.');
