import { writeFileSync, mkdirSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { z } from 'zod';
import { definePlugin } from '../plugin.js';

export const STATUS_FILE = '/tmp/metro-mcp-status.json';

const CLAUDE_DIR = join(homedir(), '.claude');
const SCRIPT_PATH = join(CLAUDE_DIR, 'metro-mcp-statusline.sh');

const SCRIPT_CONTENT = `#!/bin/bash
# Metro MCP status line for Claude Code
# Shows CDP connection status of the Metro bundler.
# Auto-generated by metro-mcp — re-run setup_statusline to regenerate.

STATUS_FILE="/tmp/metro-mcp-status.json"

if [ ! -f "$STATUS_FILE" ]; then
  printf "\\033[2mMetro ○\\033[0m\\n"
  exit 0
fi

CONNECTED=$(jq -r '.connected' "$STATUS_FILE" 2>/dev/null)
HOST=$(jq -r '.host' "$STATUS_FILE" 2>/dev/null)
PORT=$(jq -r '.port' "$STATUS_FILE" 2>/dev/null)

if [ "$CONNECTED" = "true" ]; then
  printf "\\033[32mMetro ● %s:%s\\033[0m\\n" "$HOST" "$PORT"
else
  printf "\\033[31mMetro ●\\033[0m\\n"
fi
`;

interface StatusData {
  connected: boolean;
  host: string;
  port: number;
  target: string | null;
  updatedAt: number;
}

function writeStatus(data: StatusData): void {
  try {
    writeFileSync(STATUS_FILE, JSON.stringify(data, null, 2));
  } catch {
    // ignore write errors — status bar is best-effort
  }
}

export const statuslinePlugin = definePlugin({
  name: 'statusline',
  description: 'Writes CDP connection state to a file for Claude Code status bar integration',

  async setup(ctx) {
    function write(connected: boolean): void {
      const target = ctx.cdp.getTarget();
      writeStatus({
        connected,
        host: ctx.metro.host,
        port: ctx.metro.port,
        target: target?.description ?? null,
        updatedAt: Date.now(),
      });
    }

    ctx.cdp.on('reconnected', () => write(true));
    ctx.cdp.on('disconnected', () => write(false));

    // Write initial state
    write(ctx.cdp.isConnected());

    ctx.registerTool('setup_statusline', {
      description:
        'Writes the Metro CDP connection status script to ~/.claude/metro-mcp-statusline.sh. ' +
        'Does not modify settings.json — tell the user to add it to their status line themselves ' +
        '(e.g. ask Claude: "/statusline add the script at ~/.claude/metro-mcp-statusline.sh"). ' +
        'Only works with Claude Code.',
      parameters: z.object({}),
      handler: async () => {
        mkdirSync(CLAUDE_DIR, { recursive: true });
        writeFileSync(SCRIPT_PATH, SCRIPT_CONTENT, { mode: 0o755 });
        return [
          `Metro MCP status script written to ${SCRIPT_PATH}`,
          '',
          'To add it to your Claude Code status bar, run:',
          '  /statusline add the script at ~/.claude/metro-mcp-statusline.sh',
        ].join('\n');
      },
    });
  },
});
