import { writeFileSync, readFileSync, mkdirSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { z } from 'zod';
import { definePlugin } from '../plugin.js';

export const STATUS_FILE = '/tmp/metro-mcp-status.json';

const CLAUDE_DIR = join(homedir(), '.claude');
const SCRIPT_PATH = join(CLAUDE_DIR, 'metro-mcp-statusline.sh');
const SETTINGS_PATH = join(CLAUDE_DIR, 'settings.json');

const SCRIPT_CONTENT = `#!/bin/bash
# Metro MCP status line for Claude Code
# Shows CDP connection status of the Metro bundler.
# Auto-generated by metro-mcp — re-run setup_statusline to regenerate.

STATUS_FILE="/tmp/metro-mcp-status.json"

if [ ! -f "$STATUS_FILE" ]; then
  echo "Metro: --"
  exit 0
fi

CONNECTED=$(jq -r '.connected' "$STATUS_FILE" 2>/dev/null)
HOST=$(jq -r '.host' "$STATUS_FILE" 2>/dev/null)
PORT=$(jq -r '.port' "$STATUS_FILE" 2>/dev/null)

if [ "$CONNECTED" = "true" ]; then
  printf "\\033[32mMetro \\u2713 %s:%s\\033[0m\\n" "$HOST" "$PORT"
else
  printf "\\033[31mMetro \\u2717\\033[0m\\n"
fi
`;

interface StatusData {
  connected: boolean;
  host: string;
  port: number;
  target: string | null;
  updatedAt: number;
}

function writeStatus(data: StatusData): void {
  try {
    writeFileSync(STATUS_FILE, JSON.stringify(data, null, 2));
  } catch {
    // ignore write errors — status bar is best-effort
  }
}

export const statuslinePlugin = definePlugin({
  name: 'statusline',
  description: 'Writes CDP connection state to a file for Claude Code status bar integration',

  async setup(ctx) {
    function write(connected: boolean): void {
      const target = ctx.cdp.getTarget();
      writeStatus({
        connected,
        host: ctx.metro.host,
        port: ctx.metro.port,
        target: target?.description ?? null,
        updatedAt: Date.now(),
      });
    }

    ctx.cdp.on('reconnected', () => write(true));
    ctx.cdp.on('disconnected', () => write(false));

    // Write initial state
    write(ctx.cdp.isConnected());

    ctx.registerTool('setup_statusline', {
      description:
        'Set up the Claude Code status bar to show Metro CDP connection status. ' +
        'Writes a status line script to ~/.claude/metro-mcp-statusline.sh and merges ' +
        'the statusLine config into ~/.claude/settings.json. Only works with Claude Code.',
      parameters: z.object({}),
      handler: async () => {
        mkdirSync(CLAUDE_DIR, { recursive: true });

        // Write the script
        writeFileSync(SCRIPT_PATH, SCRIPT_CONTENT, { mode: 0o755 });

        // Read existing settings (preserve all other keys)
        let settings: Record<string, unknown> = {};
        try {
          settings = JSON.parse(readFileSync(SETTINGS_PATH, 'utf-8'));
        } catch {
          // file missing or invalid JSON — start fresh
        }

        const alreadyConfigured =
          (settings.statusLine as Record<string, unknown> | undefined)?.command === SCRIPT_PATH;

        settings.statusLine = { type: 'command', command: SCRIPT_PATH };
        writeFileSync(SETTINGS_PATH, JSON.stringify(settings, null, 2) + '\n');

        if (alreadyConfigured) {
          return `Status line already configured — script refreshed at ${SCRIPT_PATH}`;
        }

        return [
          'Claude Code status bar configured.',
          `  Script:   ${SCRIPT_PATH}`,
          `  Settings: ${SETTINGS_PATH}`,
          '',
          'Open a new Claude Code session for the status bar to appear.',
        ].join('\n');
      },
    });
  },
});
